export interface PushNotificationPayload { id: string; title: string; body: string; tipo: 'warning' | 'info' | 'success'; categoria: 'venta' | 'inventario_critico' | 'ajuste' | 'sistema'; timestamp: string; data?: Record<string, any> }
export interface PushPreferences { enabled: boolean; notifyVentas: boolean; notifyInventario: boolean; notifyAjustes: boolean; soundEnabled: boolean }
const defaults: PushPreferences = { enabled: true, notifyVentas: true, notifyInventario: true, notifyAjustes: true, soundEnabled: true };
const listeners = new Set<(payload: PushNotificationPayload) => void>();
export function getPushPreferences(): PushPreferences { try { return { ...defaults, ...JSON.parse(localStorage.getItem('browser_notification_preferences') || '{}') }; } catch { return defaults; } }
export function savePushPreferences(prefs: Partial<PushPreferences>): PushPreferences { const next = { ...getPushPreferences(), ...prefs }; localStorage.setItem('browser_notification_preferences', JSON.stringify(next)); return next; }
export function playNotificationSound(_type: 'sale' | 'critico' | 'info') {}
export async function initializeNotificaciones() { return { supported: typeof Notification !== 'undefined', token: null, permission: typeof Notification === 'undefined' ? 'denied' as NotificationPermission : Notification.permission }; }
export async function requestPushPermission() { if (typeof Notification === 'undefined') return { granted: false, token: null, error: 'Este navegador no soporta notificaciones.' }; const permission = await Notification.requestPermission(); return { granted: permission === 'granted', token: null, ...(permission !== 'granted' ? { error: 'Permiso de notificaciones denegado.' } : {}) }; }
export function subscribeToPushNotifications(listener: (payload: PushNotificationPayload) => void) { listeners.add(listener); return () => listeners.delete(listener); }
export function dispatchPushAlert(params: Omit<PushNotificationPayload, 'id' | 'timestamp'>) { const prefs = getPushPreferences(); if (!prefs.enabled || (params.categoria === 'venta' && !prefs.notifyVentas) || (params.categoria === 'inventario_critico' && !prefs.notifyInventario) || (params.categoria === 'ajuste' && !prefs.notifyAjustes)) return null; const payload = { ...params, id: `notice_${Date.now()}`, timestamp: new Date().toLocaleTimeString() }; listeners.forEach((listener) => listener(payload)); if (typeof Notification !== 'undefined' && Notification.permission === 'granted') new Notification(payload.title, { body: payload.body }); return payload; }
